See this exception on Errbit: <%= app_err_url problem.app, problem %>
<% if notice = problem.notices.first %>
    <% if notice.request['url'].present? %>URL: <%= notice.request['url'] %><% end %>
    Where: <%= notice.where %>
    Occurred: <%= notice.created_at.to_s :micro %>
    Similar: <%= (notice.problem.notices_count - 1).to_s %>

    Params:
    <%= pretty_hash notice.params %>

    Session:
    <%= pretty_hash notice.session %>

    Backtrace:
    <%= notice.backtrace[0..4].map { |line| "#{line['number']}: #{line['file'].to_s.sub(/^\[PROJECT_ROOT\]/, '')} -> *#{line['method']}*" }.join "\n" %>
<% end %>

